<?php

namespace AppBundle\Entity\Repository;
use AppBundle\Entity\User;
use Doctrine\DBAL\Query\QueryBuilder;
use Doctrine\ORM\Query;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $email
     * @param User $user
     * @return User
     */
    public function getDifferentUserWithEmail($email, $user){
        /** @var \Doctrine\ORM\QueryBuilder $qb */
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('u')
            ->from("AppBundle:User", 'u')
            ->where("u.email like :email")
            ->andWhere("u.id <> :id")
            ->setParameter('email', $email)
            ->setParameter('id', $user->getId());
        return $qb->getQuery()->getOneOrNullResult();
    }
}
