<?php

namespace AppBundle\Entity\Repository;
use AppBundle\Entity\User;
use Doctrine\DBAL\Query\QueryBuilder;
use Doctrine\ORM\Query;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

}
